import { Styles } from "./styles"

export const defaultStyles: Styles = {
    control: {
        root: "mb-8",
        wrapper: "",
        label: "font-bold mb-2",
        description: "italic text-sm mb-2",
        input: "",
        error: "text-red-500 italic text-sm mb-2",
        textarea: "",
        select: "",
        option: "",
        asterisk: "text-red-500",
        required: "",
    },
    verticalLayout: {
        root: "vertical-layout",
        item: "vertical-layout-item",
    },
    horizontalLayout: {
        root: "horizontal-layout",
        item: "horizontal-layout-item",
    },
    group: {
        root: "group mb-8",
        item: "group-item",
    },
    arrayList: {
        root: "mb-8",
        legend: "flex items-center w-full mt-4",
        addButton: "flex-none",
        label: "font-bold",
        itemWrapper: "w-full",
        noData: "",
        item: "w-full",
        itemToolbar: "flex items-start gap-1",
        itemToolbarExpanded: "",
        itemLabel: "font-bold italic",
        itemContent: "-mb-4",
        itemMoveUp: "",
        itemMoveDown: "",
        itemDelete: "",
    },
    dialog: {
        root: "dialog-root",
        title: "dialog-title",
        body: "dialog-body",
        actions: "dialog-actions",
        buttonPrimary: "dialog-button-primary",
        buttonSecondary: "dialog-button-secondary",
    },
    oneOf: {
        root: "one-of",
    },
    categorization: {
        root: "categorization",
        category: "categorization-category",
        selected: "categorization-selected",
        panel: "categorization-panel",
        stepper: "categorization-stepper",
        stepperBadge: "categorization-stepper-badge",
        stepperLine: "categorization-stepper-line",
        stepperFooter: "categorization-stepper-footer",
        stepperButtonBack: "categorization-stepper-button-back",
        stepperButtonNext: "categorization-stepper-button-next",
    },
}
