import { Styles } from "./styles"

export const defaultStyles: Styles = {
    control: {
        root: "",
        wrapper: "",
        label: "font-bold mb-2",
        description: "italic text-sm mb-2",
        input: "",
        error: "text-red-500 italic text-sm mb-2",
        textarea: "",
        select: "",
        option: "",
        asterisk: "text-red-500",
        required: "",
    },
    verticalLayout: {
        root: "flex flex-col gap-8",
        item: "",
    },
    horizontalLayout: {
        root: "flex flex-row flex-wrap items-start gap-4",
        item: "flex-1 min-w-[12rem]",
    },
    group: {
        root: "group",
        content: "px-5 pt-4 pb-5 flex flex-col gap-8",
        contentNoSpacing: "",
        item: "group-item",
    },
    arrayList: {
        root: "",
        legend: "flex items-center w-full",
        addButton: "flex-none",
        label: "font-bold",
        itemWrapper: "w-full",
        noData: "",
        item: "w-full",
        itemToolbar: "flex items-start gap-1",
        itemToolbarExpanded: "",
        itemLabel: "font-bold italic",
        itemContent: "px-5 pb-5",
        itemMoveUp: "",
        itemMoveDown: "",
        itemDelete: "",
    },
    dialog: {
        root: "dialog-root",
        title: "dialog-title",
        body: "dialog-body",
        actions: "dialog-actions",
        buttonPrimary: "dialog-button-primary",
        buttonSecondary: "dialog-button-secondary",
    },
    oneOf: {
        root: "one-of",
        content: "px-5 pb-5",
        top: "pt-2",
        selector: "mt-4",
        radioHorizontal: "flex flex-wrap gap-6 items-center",
        radioVertical: "flex flex-col gap-2",
    },
    anyOf: {
        root: "any-of",
        top: "",
        panel: "px-5 pb-5",
    },
    allOf: {
        root: "all-of",
        content: "px-5 pb-5",
        top: "pt-4",
        panel: "px-5 pb-5",
        list: "flex flex-col gap-8",
    },
    categorization: {
        root: "categorization",
        category: "",
        panel: "",
        contentStepper: "px-3 pt-3",
        stepperFooter: "",
        stepperButtonBack: "",
        stepperButtonNext: "",
    },
}
